AWSTemplateFormatVersion: 2010-09-09
Description: Administrators Group
Resources:

  AdminsGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: administrators
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
 
  AdminUser:
    Type: AWS::IAM::User
    Properties:
      UserName: admin
      LoginProfile:
        Password: password
        PasswordResetRequired: true
      Tags:
        - Key: client
          Value: chinatown
        - Key: description
          Value: admin created after initial account creation to prevent the need for the root acount login
        - Key: created-by
          Value: Austin Conder 

  AddAdminToGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !!Ref AdminsGroup
      Users:
        - !Ref AdminUser
      