#!/bin/bash

filename="$1"
stackname="$2"

if [ -z "$filename" ]
  then echo "usage: create-stack filename stackname" && exit
fi

if [ -z "$stackname" ]
  then echo "usage: create-stack filename stackname" && exit
fi

aws cloudformation create-stack \
  --stack-name "$stackname" \
  --template-body file://"$filename" \
  --capabilities CAPABILITY_NAMED_IAM
