AWSTemplateFormatVersion: 2010-09-09
Description: Template to create new IAM Groups consiting of managed policies

Parameters:
  GroupName:
    Type: String
    Description: The name of the new IAM Group
  GroupPolicies:
    Type: CommaDelimitedList
  Users:
    Type: CommaDelimitedList

#        - arn:aws:iam::aws:policy/AdministratorAccess
Resources:

  IAMGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Ref GroupName
      ManagedPolicyArns: !Ref 'GroupPolicies'

  AddUsersToGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref IAMGroup
      Users: !Ref Users
