AWSTemplateFormatVersion: 2010-09-09
Description: Template to create new IAM User

Parameters:
  UserName:
    Type: String
    Description: The username for the new IAM User
  Description:
    Type: String
    Default: New IAM User
  Client:
    Type: String
    Default: chinatown
  CreatedBy:
    Type: String
    Default: Austin Conder

Resources:

  User:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref 'UserName'
      LoginProfile:
        Password: '{{resolve:secretsmanager:admin-temporary-password}}'
        PasswordResetRequired: true
      Tags:
        - Key: client
          Value: !Ref Client
        - Key: description
          Value: !Ref Description
        - Key: CreatedBy
          Value: !Ref CreatedBy

Outputs:
  UserName:
    Value: !Ref User
    Export:
      Name: UserName
  UserArn:
    Value: !GetAtt User.Arn
