AWSTemplateFormatVersion: 2010-09-09
Description: Admin temporary password

Transform: AWS::SecretsManager-2020-07-23

Resources:

  AdminTemporaryPassword:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Temporary password for initial admin account
      GenerateSecretString:
        IncludeSpace: false
        RequireEachIncludedType: true
      Name: admin-temporary-password

  AdminPasswordRotationSchedule:
    Type: AWS::SecretsManager::RotationSchedule
    Properties:
      RotateImmediatelyOnUpdate: false
      HostedRotationLambda:
        RotationType: PostgreSQLSingleUser
      SecretId: !Ref AdminTemporaryPassword
