AWSTemplateFormatVersion: 2010-09-09
Description: Admin temporary password
Resources:

  AdminTemporaryPassword:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Temporary password for initial admin account
      GenerateSecretString:
        IncludeSpace: false
        RequireEachIncludedType: true
      Name: admin-temporary-password