AWSTemplateFormatVersion: 2010-09-09
Description: Admin temporary password

Transform: AWS::SecretsManager-2020-07-23

Resources:

  AdminTemporaryPassword:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Temporary password for initial admin account
      GenerateSecretString:
        IncludeSpace: false
        RequireEachIncludedType: true
      Name: admin-temporary-password

#   MySecretRotationSchedule:
#     Type: AWS::SecretsManager::RotationSchedule
#     Properties:
#       SecretId: !Ref AdminTemporaryPassword
#       RotationLambdaARN: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:SecretsManagerMySQLRotationFunction'
#       RotationRules:
#         AutomaticallyAfterDays: 30

# Outputs:
